language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

install:
  - echo "Override default Travis install step to avoid unnecessary './gradlew assemble'."

script:
  - ./gradlew test build --daemon

after_success:
  - java -jar ./codacy-coverage-reporter-assembly.jar report -l Kotlin -r build/reports/jacoco/test/jacocoTestReport.xml
