# # # # # # # # # # # # # # # # # # # # #
#                                       #
#      Sample Plugin Configuration      #
#                                       #
# # # # # # # # # # # # # # # # # # # # #

MyString: "Hello World"

MyBoolean: true

MySection:
  AnotherBoolean: false
  MyInteger: 420