name: PocketKnife-TestPlugin
version: @VERSION@
main: de.axelrindle.pocketknife.testplugin.PocketKnifeTestPlugin
author: "Axel Rindle"
depend: [PocketKnife]
commands:
  pocketknife:
    usage: /pocketknife
    description: Access the plugin.
    permission: pocketknife.access