name: PocketKnife-TestPlugin
version: @VERSION@
main: de.axelrindle.testplugin.PocketKnifeTestPlugin
author: "Axel Rindle"
api-version: 1.13
commands:
  pocketknife:
    usage: /pocketknife
    description: Access the plugin.
    permission: pocketknife.access