name: Test

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build project
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test
    - name: Generate coverage report
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: java -jar ./codacy-coverage-reporter-assembly.jar report -l Kotlin -r api/build/reports/jacoco/test/jacocoTestReport.xml
