name: Test

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build project
      run: ./gradlew build -x test
    - name: Run tests
      run: ./gradlew test
    - name: Generate coverage report
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: java -jar ./codacy-coverage-reporter-assembly.jar report -l Kotlin -r api/build/reports/jacoco/test/jacocoTestReport.xml
    - uses: actions/upload-artifact@v1
      with:
        name: Test Reports
        path: api/build/reports
